from PyQt5 import QtCore, QtGui, QtWidgets
from rubik_solver import utils
import numpy
import matplotlib



sequence_arr = []
frontarr = []
botarr = []
backarr = []
toparr = []
leftarr = []
rightarr = []
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1599, 909)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.L1 = QtWidgets.QPushButton(self.centralwidget)
        self.L1.setGeometry(QtCore.QRect(210, 120, 61, 61))
        self.L1.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L1.setObjectName("L1")
        self.L6 = QtWidgets.QPushButton(self.centralwidget)
        self.L6.setGeometry(QtCore.QRect(350, 190, 61, 61))
        self.L6.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L6.setObjectName("L6")
        self.L7 = QtWidgets.QPushButton(self.centralwidget)
        self.L7.setGeometry(QtCore.QRect(210, 260, 61, 61))
        self.L7.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L7.setObjectName("L7")
        self.L5 = QtWidgets.QPushButton(self.centralwidget)
        self.L5.setGeometry(QtCore.QRect(280, 190, 61, 61))
        self.L5.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L5.setObjectName("L5")
        self.L4 = QtWidgets.QPushButton(self.centralwidget)
        self.L4.setGeometry(QtCore.QRect(210, 190, 61, 61))
        self.L4.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L4.setObjectName("L4")
        self.L3 = QtWidgets.QPushButton(self.centralwidget)
        self.L3.setGeometry(QtCore.QRect(350, 120, 61, 61))
        self.L3.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L3.setObjectName("L3")
        self.L2 = QtWidgets.QPushButton(self.centralwidget)
        self.L2.setGeometry(QtCore.QRect(280, 120, 61, 61))
        self.L2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L2.setObjectName("L2")
        self.L8 = QtWidgets.QPushButton(self.centralwidget)
        self.L8.setGeometry(QtCore.QRect(280, 260, 61, 61))
        self.L8.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L8.setObjectName("L8")
        self.L9 = QtWidgets.QPushButton(self.centralwidget)
        self.L9.setGeometry(QtCore.QRect(350, 260, 61, 61))
        self.L9.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.L9.setObjectName("L9")
        self.BB6 = QtWidgets.QPushButton(self.centralwidget)
        self.BB6.setGeometry(QtCore.QRect(350, 620, 61, 61))
        self.BB6.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB6.setObjectName("BB6")
        self.BB7 = QtWidgets.QPushButton(self.centralwidget)
        self.BB7.setGeometry(QtCore.QRect(210, 690, 61, 61))
        self.BB7.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB7.setObjectName("BB7")
        self.BB1 = QtWidgets.QPushButton(self.centralwidget)
        self.BB1.setGeometry(QtCore.QRect(210, 550, 61, 61))
        self.BB1.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB1.setObjectName("BB1")
        self.BB3 = QtWidgets.QPushButton(self.centralwidget)
        self.BB3.setGeometry(QtCore.QRect(350, 550, 61, 61))
        self.BB3.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB3.setObjectName("BB3")
        self.BB5 = QtWidgets.QPushButton(self.centralwidget)
        self.BB5.setGeometry(QtCore.QRect(280, 620, 61, 61))
        self.BB5.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB5.setObjectName("BB5")
        self.BB9 = QtWidgets.QPushButton(self.centralwidget)
        self.BB9.setGeometry(QtCore.QRect(350, 690, 61, 61))
        self.BB9.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB9.setObjectName("BB9")
        self.BB4 = QtWidgets.QPushButton(self.centralwidget)
        self.BB4.setGeometry(QtCore.QRect(210, 620, 61, 61))
        self.BB4.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB4.setObjectName("BB4")
        self.BB2 = QtWidgets.QPushButton(self.centralwidget)
        self.BB2.setGeometry(QtCore.QRect(280, 550, 61, 61))
        self.BB2.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB2.setObjectName("BB2")
        self.BB8 = QtWidgets.QPushButton(self.centralwidget)
        self.BB8.setGeometry(QtCore.QRect(280, 690, 61, 61))
        self.BB8.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.BB8.setObjectName("BB8")
        self.R9 = QtWidgets.QPushButton(self.centralwidget)
        self.R9.setGeometry(QtCore.QRect(650, 690, 61, 61))
        self.R9.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R9.setObjectName("R9")
        self.B6 = QtWidgets.QPushButton(self.centralwidget)
        self.B6.setGeometry(QtCore.QRect(630, 190, 61, 61))
        self.B6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B6.setObjectName("B6")
        self.B5 = QtWidgets.QPushButton(self.centralwidget)
        self.B5.setGeometry(QtCore.QRect(560, 190, 61, 61))
        self.B5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B5.setObjectName("B5")
        self.R2 = QtWidgets.QPushButton(self.centralwidget)
        self.R2.setGeometry(QtCore.QRect(580, 550, 61, 61))
        self.R2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R2.setObjectName("R2")
        self.R6 = QtWidgets.QPushButton(self.centralwidget)
        self.R6.setGeometry(QtCore.QRect(650, 620, 61, 61))
        self.R6.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R6.setObjectName("R6")
        self.B7 = QtWidgets.QPushButton(self.centralwidget)
        self.B7.setGeometry(QtCore.QRect(490, 260, 61, 61))
        self.B7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B7.setObjectName("B7")
        self.R1 = QtWidgets.QPushButton(self.centralwidget)
        self.R1.setGeometry(QtCore.QRect(510, 550, 61, 61))
        self.R1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R1.setObjectName("R1")
        self.B4 = QtWidgets.QPushButton(self.centralwidget)
        self.B4.setGeometry(QtCore.QRect(490, 190, 61, 61))
        self.B4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B4.setObjectName("B4")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(490, 120, 61, 61))
        self.B1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B1.setObjectName("B1")
        self.B9 = QtWidgets.QPushButton(self.centralwidget)
        self.B9.setGeometry(QtCore.QRect(630, 260, 61, 61))
        self.B9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B9.setObjectName("B9")
        self.R7 = QtWidgets.QPushButton(self.centralwidget)
        self.R7.setGeometry(QtCore.QRect(510, 690, 61, 61))
        self.R7.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R7.setObjectName("R7")
        self.B3 = QtWidgets.QPushButton(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(630, 120, 61, 61))
        self.B3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B3.setObjectName("B3")
        self.R4 = QtWidgets.QPushButton(self.centralwidget)
        self.R4.setGeometry(QtCore.QRect(510, 620, 61, 61))
        self.R4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R4.setObjectName("R4")
        self.R5 = QtWidgets.QPushButton(self.centralwidget)
        self.R5.setGeometry(QtCore.QRect(580, 620, 61, 61))
        self.R5.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R5.setObjectName("R5")
        self.R3 = QtWidgets.QPushButton(self.centralwidget)
        self.R3.setGeometry(QtCore.QRect(650, 550, 61, 61))
        self.R3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R3.setObjectName("R3")
        self.B2 = QtWidgets.QToolButton(self.centralwidget)
        self.B2.setGeometry(QtCore.QRect(560, 120, 61, 61))
        self.B2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B2.setObjectName("B2")
        self.R8 = QtWidgets.QPushButton(self.centralwidget)
        self.R8.setGeometry(QtCore.QRect(580, 690, 61, 61))
        self.R8.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.R8.setObjectName("R8")
        self.B8 = QtWidgets.QPushButton(self.centralwidget)
        self.B8.setGeometry(QtCore.QRect(560, 260, 61, 61))
        self.B8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.B8.setObjectName("B8")
        self.T9 = QtWidgets.QPushButton(self.centralwidget)
        self.T9.setGeometry(QtCore.QRect(920, 690, 61, 61))
        self.T9.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T9.setObjectName("T9")
        self.F6 = QtWidgets.QPushButton(self.centralwidget)
        self.F6.setGeometry(QtCore.QRect(920, 190, 61, 61))
        self.F6.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F6.setObjectName("F6")
        self.F5 = QtWidgets.QPushButton(self.centralwidget)
        self.F5.setGeometry(QtCore.QRect(850, 190, 61, 61))
        self.F5.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F5.setObjectName("F5")
        self.T2 = QtWidgets.QPushButton(self.centralwidget)
        self.T2.setGeometry(QtCore.QRect(850, 550, 61, 61))
        self.T2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T2.setObjectName("T2")
        self.T6 = QtWidgets.QPushButton(self.centralwidget)
        self.T6.setGeometry(QtCore.QRect(920, 620, 61, 61))
        self.T6.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T6.setObjectName("T6")
        self.F7 = QtWidgets.QPushButton(self.centralwidget)
        self.F7.setGeometry(QtCore.QRect(780, 260, 61, 61))
        self.F7.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F7.setObjectName("F7")
        self.T1 = QtWidgets.QPushButton(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(780, 550, 61, 61))
        self.T1.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T1.setObjectName("T1")
        self.F4 = QtWidgets.QPushButton(self.centralwidget)
        self.F4.setGeometry(QtCore.QRect(780, 190, 61, 61))
        self.F4.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F4.setObjectName("F4")
        self.F1 = QtWidgets.QPushButton(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(780, 120, 61, 61))
        self.F1.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F1.setObjectName("F1")
        self.F9 = QtWidgets.QPushButton(self.centralwidget)
        self.F9.setGeometry(QtCore.QRect(920, 260, 61, 61))
        self.F9.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F9.setObjectName("F9")
        self.T7 = QtWidgets.QPushButton(self.centralwidget)
        self.T7.setGeometry(QtCore.QRect(780, 690, 61, 61))
        self.T7.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T7.setObjectName("T7")
        self.F3 = QtWidgets.QPushButton(self.centralwidget)
        self.F3.setGeometry(QtCore.QRect(920, 120, 61, 61))
        self.F3.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F3.setObjectName("F3")
        self.T4 = QtWidgets.QPushButton(self.centralwidget)
        self.T4.setGeometry(QtCore.QRect(780, 620, 61, 61))
        self.T4.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T4.setObjectName("T4")
        self.T5 = QtWidgets.QPushButton(self.centralwidget)
        self.T5.setGeometry(QtCore.QRect(850, 620, 61, 61))
        self.T5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T5.setObjectName("T5")
        self.T3 = QtWidgets.QPushButton(self.centralwidget)
        self.T3.setGeometry(QtCore.QRect(920, 550, 61, 61))
        self.T3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T3.setObjectName("T3")
        self.F2 = QtWidgets.QPushButton(self.centralwidget)
        self.F2.setGeometry(QtCore.QRect(850, 120, 61, 61))
        self.F2.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F2.setObjectName("F2")
        self.T8 = QtWidgets.QPushButton(self.centralwidget)
        self.T8.setGeometry(QtCore.QRect(850, 690, 61, 61))
        self.T8.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.T8.setObjectName("T8")
        self.F8 = QtWidgets.QPushButton(self.centralwidget)
        self.F8.setGeometry(QtCore.QRect(850, 260, 61, 61))
        self.F8.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.F8.setObjectName("F8")
        self.leftname = QtWidgets.QTextEdit(self.centralwidget)
        self.leftname.setGeometry(QtCore.QRect(230, 0, 171, 61))
        self.leftname.setObjectName("leftname")
        self.bottomname = QtWidgets.QTextEdit(self.centralwidget)
        self.bottomname.setGeometry(QtCore.QRect(510, 0, 171, 61))
        self.bottomname.setObjectName("bottomname")
        self.frontname = QtWidgets.QTextEdit(self.centralwidget)
        self.frontname.setGeometry(QtCore.QRect(800, 0, 171, 61))
        self.frontname.setObjectName("frontname")
        self.backname = QtWidgets.QTextEdit(self.centralwidget)
        self.backname.setGeometry(QtCore.QRect(230, 340, 171, 101))
        self.backname.setObjectName("backname")
        self.rightname = QtWidgets.QTextEdit(self.centralwidget)
        self.rightname.setGeometry(QtCore.QRect(520, 340, 171, 101))
        self.rightname.setAutoFillBackground(False)
        self.rightname.setObjectName("rightname")
        self.topname = QtWidgets.QTextEdit(self.centralwidget)
        self.topname.setGeometry(QtCore.QRect(810, 330, 171, 101))
        self.topname.setObjectName("topname")
        self.FinishButton = QtWidgets.QPushButton(self.centralwidget)
        self.FinishButton.setGeometry(QtCore.QRect(990, 120, 221, 621))
        self.FinishButton.setObjectName("FinishButton")
        self.BACKFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.BACKFACE.setGeometry(QtCore.QRect(250, 80, 113, 20))
        self.BACKFACE.setObjectName("BACKFACE")
        self.BACKFACE.setPlaceholderText("Enter Face")
        self.RIGHTFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.RIGHTFACE.setGeometry(QtCore.QRect(250, 500, 113, 20))
        self.RIGHTFACE.setObjectName("RIGHTFACE")
        self.RIGHTFACE.setPlaceholderText("Enter Face")
        self.TOPFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.TOPFACE.setGeometry(QtCore.QRect(830, 500, 113, 20))
        self.TOPFACE.setObjectName("TOPFACE")
        self.TOPFACE.setPlaceholderText("Enter Face")
        self.LEFTFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.LEFTFACE.setGeometry(QtCore.QRect(830, 80, 113, 20))
        self.LEFTFACE.setObjectName("LEFTFACE")
        self.LEFTFACE.setPlaceholderText("Enter Face")
        self.BOTTOMFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.BOTTOMFACE.setGeometry(QtCore.QRect(530, 90, 113, 20))
        self.BOTTOMFACE.setObjectName("BOTTOMFACE")
        self.BOTTOMFACE.setPlaceholderText("Enter Face")
        self.FRONTFACE = QtWidgets.QLineEdit(self.centralwidget)
        self.FRONTFACE.setGeometry(QtCore.QRect(560, 500, 113, 20))
        self.FRONTFACE.setObjectName("FRONTFACE")
        self.FRONTFACE.setPlaceholderText("Enter Face")
        self.FinishButton.clicked.connect(self.save)
        self.L1.clicked.connect(self.delete)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1599, 21))
        self.menubar.setObjectName("menubar")
        self.menuRubixCube_Sontag = QtWidgets.QMenu(self.menubar)
        self.menuRubixCube_Sontag.setObjectName("menuRubixCube_Sontag")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRubixCube_Sontag.menuAction())
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def delete(self):
        sequence_arr = []
        frontarr = []
        botarr = []
        backarr = []
        toparr = []
        leftarr = []
        rightarr = []
        allarr = []
        print("ARRAYS HAVE BEEN CLEARED")
        print("ENTER A NEW PATTERN")

     

            
           

    def save(self):
        cube = []
        back_face = self.BACKFACE.text()
        front_face = self.FRONTFACE.text()
        left_face = self.LEFTFACE.text()
        right_face = self.RIGHTFACE.text()
        top_face = self.TOPFACE.text()
        bot_face = self.BOTTOMFACE.text()
        
        cube.append(top_face)
        cube.append(left_face)
        cube.append(front_face)
        cube.append(right_face)
        cube.append(back_face)
        cube.append(bot_face)


        SequenceString = cube[0]+cube[1]+cube[2]+cube[3]+cube[4]+cube[5]


        str1 = ""
        for ele in SequenceString:
                str1 += ele 
        print(str1)

        Solved_Sequence = utils.solve(str1, 'Kociemba')
        Cfop = utils.solve(str1, 'CFOP')
        print(str(Cfop) + " CFOP")
        print(str(Solved_Sequence) + 'KOCIEMBA')
        print(str(Solved_Sequence) +  'follow the steps to complete the cube'

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.L1.setText(_translate("MainWindow", "L1"))
        self.L6.setText(_translate("MainWindow", "L6"))
        self.L7.setText(_translate("MainWindow", "L7"))
        self.L5.setText(_translate("MainWindow", "L5"))
        self.L4.setText(_translate("MainWindow", "L4"))
        self.L3.setText(_translate("MainWindow", "L3"))
        self.L2.setText(_translate("MainWindow", "L2"))
        self.L8.setText(_translate("MainWindow", "L8"))
        self.L9.setText(_translate("MainWindow", "L9"))
        self.BB6.setText(_translate("MainWindow", "BB6"))
        self.BB7.setText(_translate("MainWindow", "BB7"))
        self.BB1.setText(_translate("MainWindow", "BB1"))
        self.BB3.setText(_translate("MainWindow", "BB3"))
        self.BB5.setText(_translate("MainWindow", "BB5"))
        self.BB9.setText(_translate("MainWindow", "BB9"))
        self.BB4.setText(_translate("MainWindow", "BB4"))
        self.BB2.setText(_translate("MainWindow", "BB2"))
        self.BB8.setText(_translate("MainWindow", "BB8"))
        self.R9.setText(_translate("MainWindow", "R9"))
        self.B6.setText(_translate("MainWindow", "B6"))
        self.B5.setText(_translate("MainWindow", "B5"))
        self.R2.setText(_translate("MainWindow", "R2"))
        self.R6.setText(_translate("MainWindow", "R6"))
        self.B7.setText(_translate("MainWindow", "B7"))
        self.R1.setText(_translate("MainWindow", "R1"))
        self.B4.setText(_translate("MainWindow", "B4"))
        self.B1.setText(_translate("MainWindow", "B1"))
        self.B9.setText(_translate("MainWindow", "B9"))
        self.R7.setText(_translate("MainWindow", "R7"))
        self.B3.setText(_translate("MainWindow", "B3"))
        self.R4.setText(_translate("MainWindow", "R4"))
        self.R5.setText(_translate("MainWindow", "R5"))
        self.R3.setText(_translate("MainWindow", "R3"))
        self.B2.setText(_translate("MainWindow", "B2"))
        self.R8.setText(_translate("MainWindow", "R8"))
        self.B8.setText(_translate("MainWindow", "B8"))
        self.T9.setText(_translate("MainWindow", "T9"))
        self.F6.setText(_translate("MainWindow", "F6"))
        self.F5.setText(_translate("MainWindow", "F5"))
        self.T2.setText(_translate("MainWindow", "T2"))
        self.T6.setText(_translate("MainWindow", "T6"))
        self.F7.setText(_translate("MainWindow", "F7"))
        self.T1.setText(_translate("MainWindow", "T1"))
        self.F4.setText(_translate("MainWindow", "F4"))
        self.F1.setText(_translate("MainWindow", "F1"))
        self.F9.setText(_translate("MainWindow", "F9"))
        self.T7.setText(_translate("MainWindow", "T7"))
        self.F3.setText(_translate("MainWindow", "F3"))
        self.T4.setText(_translate("MainWindow", "T4"))
        self.T5.setText(_translate("MainWindow", "T5"))
        self.T3.setText(_translate("MainWindow", "T3"))
        self.F2.setText(_translate("MainWindow", "F2"))
        self.T8.setText(_translate("MainWindow", "T8"))
        self.F8.setText(_translate("MainWindow", "F8"))
        self.leftname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">BACK</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.bottomname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">BOTTOM</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.frontname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">LEFT</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.backname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">RIGHT</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.rightname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">FRONT</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.topname.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\">TOP</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:28pt; font-weight:600; font-style:italic; text-decoration: underline;\"><br /></p></body></html>"))
        self.FinishButton.setText(_translate("MainWindow", "Click When Finished Inputting Cube State"))
        self.menuRubixCube_Sontag.setTitle(_translate("MainWindow", "RubixCube Sontag"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
